{% set name = "django-rest-polymorphic" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2960f58ed9a8bb0d42bc72c8ffaadfbd7f37d2573d42a1cd9a6460f3d572b519

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - django
    - django_polymorphic
    - djangorestframework
    - python
    - six

test:
  imports:
    - rest_polymorphic

about:
  home: https://github.com/apirobot/django-rest-polymorphic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Polymorphic serializers for Django REST Framework.
  dev_url: https://github.com/apirobot/django-rest-polymorphic

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
